### ISSUE TITLE
Implement User Friendly Regex for ApiKeyBinding Subpaths

### ISSUE THREAD

**Issue by frankgreco** [northwesternmutual/kanali#81]
#### Definitions
A user friendly regex will be a string that represents an http path where regular expressions can be defined in between path segments. Note that this is different than a plan regular expression as the `/` character must be escaped.

#### Problem
Consider the following `ApiKeyBinding` `subpath` field:

```yaml
subpaths:
- path: /foo/[A-z]*
  rule:
    verbs:
    - GET
- path: /foo/*
  rule:
    verbs:
    - POST
- path: /[A-z]*
  rule:
    verbs:
    - PUT
- path: /[A-Za-z]*
  rule:
    verbs:
    - DELETE
```

Now, consider the following target path inputs and the issues that arise:
* `/foo/bar/car`
  * matches both first and second subpath
  * rule one is a subset of rule two
* `/frank`
  * matches subpaths three and four
  * subpaths three and four are equal

#### Solutions
* Have `kanalictl` disallow `ApiKeyBinding` specs that have equal regular expressions.
* Have  `kanalictl` reduce expressions before applying the spec to the apiserver (e.g `/foo/*` -> `/foo`)

With `kanalictl` performing the above operations, our original `subpaths` field reduces to the following:

```yaml
subpaths:
- path: /foo/[A-z]*
  rule:
    verbs:
    - GET
- path: /foo
  rule:
    verbs:
    - POST
- path: /[A-z]*
  rule:
    verbs:
    - PUT
```

Internally, our subpath tree would be constructed as follows:

```sh
     root
     /  \
  foo   [A-z]*      
   |
 [A-z]*
```

Here is the pseudo code that would correspond to a search for the rule matching a given target path:

```go
type node struct {
	children map[string]*node
	value    *Path
}

func (n *node) getRule(targetPath string) *v2.Rule {
  if !validPreconditions(n, targetPath) {
		return nil
	}

  for _, part := range strings.Split(targetPath, "/") {
    key := getMostStrictChild(path, n.children)
    if key == nil {
      break
    } else {
      n = n.children[key]
    }
  }

  return n.value.Rule // if nil, then the default rule for that key is used
}

func getMostStrictChild(pathSegment string, children map[string]*node) *string {
  var cur *string
  for k, _ := range children {
    if result, err := regexp.MatchString(k, pathSegment); err != nil || !result {
      continue
    }
    if isLessBroadOfRegex(k, cur) {
      cur = k
    }
  }
  return cur
}
```

#### Considerations
* What happens when an `ApiKeyBinding` spec is not applied via `kanalictl`
